CREATE TABLE "public"."domain" (
  "id"          bigint                   GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."Teams_id_seq") NOT NULL,
  "created_at"  timestamp with time zone NOT NULL DEFAULT now(),
  "code"        character varying        NOT NULL,
  "description" character varying,
  "enabled"     boolean,
  CONSTRAINT "teams_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."domain"
  ENABLE ROW LEVEL SECURITY;

CREATE POLICY "catalog_manage" ON "public"."domain"
  FOR ALL
  TO "authenticated"
  USING ((public.crm_current_role() = ANY (ARRAY['admin'::text, 'coordinador'::text])))
  WITH CHECK ((public.crm_current_role() = ANY (ARRAY['admin'::text, 'coordinador'::text])));

CREATE POLICY "catalog_read" ON "public"."domain"
  FOR SELECT
  TO "authenticated"
  USING ((public.crm_current_role() = ANY (ARRAY['admin'::text, 'coordinador'::text, 'comercial'::text])));

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "public"."domain" TO "appsheet_user";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."domain" TO "postgres", "service_role";

COMMENT ON TABLE "public"."domain" IS 'Tipos de Dominio';

REVOKE ALL ON TABLE "public"."domain" FROM "authenticated";

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "public"."domain" TO "authenticated";
