CREATE TABLE "public"."opportunity_orders" (
  "opportunity_id" bigint            NOT NULL,
  "fecha_inicio"   date,
  "fecha_fin"      date,
  "com_vendedor"   real,
  "com_comprador"  real,
  "pvp_inicial"    bigint,
  "pvp_actual"     bigint,
  "pvp_estimado"   bigint,
  "memo"           character varying,
  "domicilio"      character varying,
  "rebajas"        integer           DEFAULT 0,
  "health"         integer,
  "id"             bigint            GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  CONSTRAINT "oportunity_orders_opportunity_id_fkey" FOREIGN KEY (opportunity_id) REFERENCES public.opportunities(id),
  CONSTRAINT "opportunity_orders_health_check" CHECK (((health >= 1) AND (health <= 10))),
  CONSTRAINT "opportunity_orders_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."opportunity_orders"
  ENABLE ROW LEVEL SECURITY;

CREATE INDEX idx_opportunity_orders_opportunity_id ON public.opportunity_orders USING btree (opportunity_id);

CREATE POLICY "orders_delete_by_opportunity" ON "public"."opportunity_orders"
  FOR DELETE
  TO "authenticated"
  USING (public.crm_can_write_opportunity(opportunity_id));

CREATE POLICY "orders_insert_by_opportunity" ON "public"."opportunity_orders"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (public.crm_can_write_opportunity(opportunity_id));

CREATE POLICY "orders_select_by_opportunity" ON "public"."opportunity_orders"
  FOR SELECT
  TO "authenticated"
  USING (public.crm_can_read_opportunity(opportunity_id));

CREATE POLICY "orders_update_by_opportunity" ON "public"."opportunity_orders"
  FOR UPDATE
  TO "authenticated"
  USING (public.crm_can_write_opportunity(opportunity_id))
  WITH CHECK (public.crm_can_write_opportunity(opportunity_id));

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "public"."opportunity_orders" TO "appsheet_user";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."opportunity_orders" TO "postgres", "service_role";

COMMENT ON TABLE "public"."opportunity_orders" IS 'Oportunidad Encargos';

REVOKE ALL ON TABLE "public"."opportunity_orders" FROM "authenticated";

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "public"."opportunity_orders" TO "authenticated";
