CREATE TABLE "public"."opportunity_contacts" (
  "id"               bigint                   GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."order_contacts_id_seq") NOT NULL,
  "created_at"       timestamp with time zone NOT NULL DEFAULT now(),
  "opportunity_id"   bigint,
  "fecha"            date,
  "contact_id"       bigint,
  "memo"             character varying,
  "resultado"        boolean,
  "domicilio"        character varying,
  "event_type"       text                     NOT NULL DEFAULT 'legacy'::text,
  "actor_profile_id" bigint,
  "effective_at"     timestamp with time zone,
  "metadata"         jsonb                    NOT NULL DEFAULT '{}'::jsonb,
  "parent_event_id"  bigint,
  "updated_at"       timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "oportunity_contacts_oportunity_id_fkey" FOREIGN KEY (opportunity_id) REFERENCES public.opportunities(id),
  CONSTRAINT "opportunity_contacts_event_type_check"
    CHECK
    ((event_type = ANY (ARRAY['legacy'::text, 'activity'::text, 'note'::text, 'call'::text, 'valuation'::text, 'valuation_updated'::text, 'rg'::text, 'rg_updated'::text,
    'lead_created'::text,
    'lead_imported'::text,
    'lead_updated'::text, 'lead_deleted'::text, 'phase_changed'::text, 'visit_created'::text, 'visit_updated'::text, 'order_created'::text, 'order_updated'::text,
    'document_uploaded'::text, 'document_viewed'::text]))),
  CONSTRAINT "order_contacts_pkey" PRIMARY KEY (id),
  CONSTRAINT "opportunity_contacts_parent_event_id_fkey" FOREIGN KEY (parent_event_id) REFERENCES public.opportunity_contacts(id) ON DELETE SET NULL,
  CONSTRAINT "opportunity_contacts_actor_profile_id_fkey" FOREIGN KEY (actor_profile_id) REFERENCES public.profiles(id) ON DELETE SET NULL
);

ALTER TABLE "public"."opportunity_contacts"
  ENABLE ROW LEVEL SECURITY;

CREATE INDEX idx_opportunity_contacts_actor_profile_id ON public.opportunity_contacts USING btree (actor_profile_id)
  WHERE (actor_profile_id IS NOT NULL);

CREATE INDEX idx_opportunity_contacts_event_type_fecha ON public.opportunity_contacts USING btree (event_type, fecha DESC);

CREATE INDEX idx_opportunity_contacts_opportunity_event_created ON public.opportunity_contacts USING btree (opportunity_id, event_type, created_at DESC);

CREATE TRIGGER crm_prepare_opportunity_contact_trigger
  BEFORE INSERT OR UPDATE ON public.opportunity_contacts
  FOR EACH ROW
  EXECUTE FUNCTION public.crm_prepare_opportunity_contact();

CREATE POLICY "contacts_insert_by_opportunity" ON "public"."opportunity_contacts"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (public.crm_can_write_opportunity(opportunity_id));

CREATE POLICY "contacts_select_by_opportunity" ON "public"."opportunity_contacts"
  FOR SELECT
  TO "authenticated"
  USING (public.crm_can_read_opportunity(opportunity_id));

CREATE POLICY "contacts_update_by_opportunity" ON "public"."opportunity_contacts"
  FOR UPDATE
  TO "authenticated"
  USING (public.crm_can_write_opportunity(opportunity_id))
  WITH CHECK (public.crm_can_write_opportunity(opportunity_id));

GRANT INSERT, SELECT, UPDATE ON TABLE "public"."opportunity_contacts" TO "appsheet_user";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."opportunity_contacts" TO "postgres", "service_role";

COMMENT ON TABLE "public"."opportunity_contacts" IS 'Oportunidad Contactos';

REVOKE ALL ON TABLE "public"."opportunity_contacts" FROM "authenticated";

GRANT INSERT, SELECT, UPDATE ON TABLE "public"."opportunity_contacts" TO "authenticated";
