CREATE TABLE "public"."opportunity_documentation_cases" (
  "id"             bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "opportunity_id" bigint                   NOT NULL,
  "state"          jsonb                    NOT NULL DEFAULT '{}'::jsonb,
  "updated_by"     text,
  "created_at"     timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"     timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "opportunity_documentation_cases_opportunity_id_fkey" FOREIGN KEY (opportunity_id) REFERENCES public.opportunities(id) ON DELETE CASCADE,
  CONSTRAINT "opportunity_documentation_cases_opportunity_id_key" UNIQUE (opportunity_id),
  CONSTRAINT "opportunity_documentation_cases_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."opportunity_documentation_cases"
  ENABLE ROW LEVEL SECURITY;

CREATE POLICY "documentation_cases_delete" ON "public"."opportunity_documentation_cases"
  FOR DELETE
  TO "authenticated"
  USING (public.crm_can_write_opportunity(opportunity_id));

CREATE POLICY "documentation_cases_insert" ON "public"."opportunity_documentation_cases"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (public.crm_can_write_opportunity(opportunity_id));

CREATE POLICY "documentation_cases_select" ON "public"."opportunity_documentation_cases"
  FOR SELECT
  TO "authenticated"
  USING (public.crm_can_read_opportunity(opportunity_id));

CREATE POLICY "documentation_cases_update" ON "public"."opportunity_documentation_cases"
  FOR UPDATE
  TO "authenticated"
  USING (public.crm_can_write_opportunity(opportunity_id))
  WITH CHECK (public.crm_can_write_opportunity(opportunity_id));

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "public"."opportunity_documentation_cases" TO "appsheet_user";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."opportunity_documentation_cases" TO "postgres", "service_role";

REVOKE ALL ON TABLE "public"."opportunity_documentation_cases" FROM "authenticated";

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "public"."opportunity_documentation_cases" TO "authenticated";
