CREATE TABLE "public"."phases" (
  "id"         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "name"       character varying        NOT NULL,
  "enabled"    boolean,
  CONSTRAINT "phases_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."phases"
  ENABLE ROW LEVEL SECURITY;

CREATE POLICY "catalog_manage" ON "public"."phases"
  FOR ALL
  TO "authenticated"
  USING ((public.crm_current_role() = ANY (ARRAY['admin'::text, 'coordinador'::text])))
  WITH CHECK ((public.crm_current_role() = ANY (ARRAY['admin'::text, 'coordinador'::text])));

CREATE POLICY "catalog_read" ON "public"."phases"
  FOR SELECT
  TO "authenticated"
  USING ((public.crm_current_role() = ANY (ARRAY['admin'::text, 'coordinador'::text, 'comercial'::text])));

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "public"."phases" TO "appsheet_user";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."phases" TO "postgres", "service_role";

COMMENT ON TABLE "public"."phases" IS 'Tipos de Fases';

REVOKE ALL ON TABLE "public"."phases" FROM "authenticated";

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "public"."phases" TO "authenticated";
