CREATE TABLE "public"."profiles" (
  "id"         bigint                   GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."Users_id_seq") NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "rol"        text,
  "name"       text,
  "enabled"    boolean,
  "auth_id"    uuid,
  CONSTRAINT "Users_pkey" PRIMARY KEY (id),
  CONSTRAINT "users_auth_id_fkey" FOREIGN KEY (auth_id) REFERENCES auth.users(id),
  CONSTRAINT "users_name_key" UNIQUE (name)
);

ALTER TABLE "public"."profiles"
  ENABLE ROW LEVEL SECURITY;

CREATE POLICY "profiles_delete_by_manager" ON "public"."profiles"
  FOR DELETE
  TO "authenticated"
  USING ((public.crm_current_role() = ANY (ARRAY['admin'::text, 'coordinador'::text])));

CREATE POLICY "profiles_insert_by_manager" ON "public"."profiles"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((public.crm_current_role() = ANY (ARRAY['admin'::text, 'coordinador'::text])));

CREATE POLICY "profiles_select_by_role" ON "public"."profiles"
  FOR SELECT
  TO "authenticated"
  USING (((auth_id = auth.uid()) OR (public.crm_current_role() = ANY (ARRAY['admin'::text, 'coordinador'::text]))));

CREATE POLICY "profiles_update_by_manager" ON "public"."profiles"
  FOR UPDATE
  TO "authenticated"
  USING ((public.crm_current_role() = ANY (ARRAY['admin'::text, 'coordinador'::text])))
  WITH CHECK ((public.crm_current_role() = ANY (ARRAY['admin'::text, 'coordinador'::text])));

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "public"."profiles" TO "appsheet_user";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."profiles" TO "postgres", "service_role";

COMMENT ON TABLE "public"."profiles" IS 'Perfil y Roles del Usuario';

REVOKE ALL ON TABLE "public"."profiles" FROM "authenticated";

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "public"."profiles" TO "authenticated";
