CREATE TABLE "public"."sources" (
  "id"         bigint                   GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."Sources_id_seq") NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "digital"    boolean,
  "code"       character varying,
  "enabled"    boolean,
  CONSTRAINT "Sources_pkey" PRIMARY KEY (id),
  CONSTRAINT "sources_code_key" UNIQUE (code)
);

ALTER TABLE "public"."sources"
  ENABLE ROW LEVEL SECURITY;

CREATE POLICY "catalog_manage" ON "public"."sources"
  FOR ALL
  TO "authenticated"
  USING ((public.crm_current_role() = ANY (ARRAY['admin'::text, 'coordinador'::text])))
  WITH CHECK ((public.crm_current_role() = ANY (ARRAY['admin'::text, 'coordinador'::text])));

CREATE POLICY "catalog_read" ON "public"."sources"
  FOR SELECT
  TO "authenticated"
  USING ((public.crm_current_role() = ANY (ARRAY['admin'::text, 'coordinador'::text, 'comercial'::text])));

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "public"."sources" TO "appsheet_user";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."sources" TO "postgres", "service_role";

COMMENT ON TABLE "public"."sources" IS 'Tipos de Origenes';

REVOKE ALL ON TABLE "public"."sources" FROM "authenticated";

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE "public"."sources" TO "authenticated";
